FROM node:18.12.1-alpine as todo-api
LABEL maintainer="ponyashcat228@gmail.com"
WORKDIR /usr/src/app
ENV NODE_ENV=production
COPY build .
EXPOSE 5050
RUN ["yarn", "install"]
ENTRYPOINT ["yarn", "node", "app/app.js"]