FROM node:18.12.1-alpine as todo-api
LABEL maintainer="ponyashcat228@gmail.com"
WORKDIR /usr/src/app
ENV NODE_ENV=production
EXPOSE 5050
RUN corepack enable && \
    corepack prepare yarn@stable --activate && \
    corepack prepare yarn@3.3.0 --activate
COPY build .
RUN ["yarn", "install"]
ENTRYPOINT ["yarn", "node", "app/app.js"]