version: "3.6"
services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    secrets:
      - mongo_password
    networks:
      - todo-boilerplate-net
    volumes:
      - todo-boilerplate-db:/data/db
  backend:
    image: todo-api-boilerplate
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
    env_file:
      - prod.env
    networks:
      - todo-boilerplate-net
    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
secrets:
  mongo_password:
    file: ./secrets/db_pass

networks:
  todo-boilerplate-net:
    driver: bridge

volumes:
  todo-boilerplate-db: