version: "3.5"
services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    secrets:
      - mongo_password
  backend:
    restart: always
    environment:
      - NODE_ENV=production
    build: 
      context: .
      dockerfile: docker/api/dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - db
secrets:
  mongo_password:
    file: ./docker/mongo/secrets/db_pass