version: '3.5'

services:
  app-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    ports:
      - 27017:27017
    secrets:
      - mongo_password

secrets:
  mongo_password:
    file: ./secrets/db_pass